[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "6NthZpToN6MSrbnSir1e8oYioV6Ko1cTSqPip6gXaYiz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/marinaganopolsky/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
